#!/usr/bin/env python
# -*- coding: utf-8 -*-

from AGM import *
from parseAGM import *
from pddlAGM import *
import sys

ret = 0
try:
	if len(sys.argv)==3:
		inputFile   = sys.argv[1]
		outputFile  = sys.argv[2]
		agmData = AGMFileDataParsing.fromFile(inputFile, verbose=False)
		agmData.generatePDDL(outputFile)
	else:
		print '\n'+sys.argv[0], ' <inputFile.agm>  <outputFile.pddl>\n'
		ret = 1
except:
	print 'Error'
	ret = -1
	
sys.exit(ret)
