#!/usr/bin/env python
# -*- coding: utf-8 -*-

from AGM import *
from parseAGM import *
from pddlAGM import *
import sys

print '\n'
if len(sys.argv)==3:
	inputFile   = sys.argv[1]
	outputFile  = sys.argv[2]
	agmData = AGMFileDataParsing.fromFile(inputFile, verbose=False)
	agmData.generatePDDL(outputFile)
else:
	print '\n'+sys.argv[0], ' <inputFile.agm>  <outputFile.pddl>\n'
