(define (problem quieroPentagono)
	(:domain crearFiguras)
	(:objects P1 P2 P3 P4 P5)
	(:init	(A P1)
		(B P2)
		(C P3)
		(D P4)
		(E P5)
	)
	(:goal (and 	(unido P1 P2)
			(unido P2 P3)
			(unido P3 P4)
			(unido P4 P5)
			(unido P5 P1)
		)
	)
)