(define (problem quieroPentagono)
	(:domain AGGL)
	(:objects P1 P2 P3 P4 P5)
	(:init	(isA P1)
		(isB P2)
		(isC P3)
		(isD P4)
		(isE P5)
	)
	(:goal (and 	(unido P1 P2)
			(unido P2 P3)
			(unido P3 P4)
			(unido P4 P5)
			(unido P5 P1)
		)
	)
)